name = "Tarik"
#print(len(name))
#print(name.find("t"))
#print(name.capitalize())
#print(name.upper())
#print(name.lower())
#print(name.isdigit())
#print(name.isalpha())
#print(name.count())
#print(name.replace("T", "W"))
#print(name*10)
